blueprint:
  name: Panel_test
  description: "Konfiguracja panelu"

  source_url: https://github.com/KatarzynaBanczyk/Panel_test/blob/main/blue.yaml
  domain: automation
  homeassistant:
    min_version: 2022.11.1

  input:
    ##### MAIN NAME #####
    nspanel_name:
      name: ESPhome Node Name
      description: '* *here you have to enter exactly the same **"device_name"** you entered in the Esphome file*'
      default: [test]
      selector:
        text: {}

    language:
      name: Language for NSPanel
      default: "EN"
      selector:
        select:
          mode: dropdown
          options:
            - label: "English"
              value: ENG
            - label: "German"
