blueprint:
  name: Shelly i4 4 Buttons actions
  description: This blueprint is for the Shelly i4 setup as button. It is for general use.
  domain: automation
  input:
    button:
      name: button
      description: Choose Shelly i4
      selector:
        device:
          manufacturer: Shelly
          model: SNSN-0024X
          multiple: false
    downb1:
      name: Down Button 1
      description: Action to run when SHORT press
      default: []
      selector:
        action: {}
    upb1:
      name: up Button 1
      description: Action to run when SHORT press
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
  - platform: device
    device_id: !input button
    domain: shelly
    type: btn_down
    subtype: button1
    id: btn1_down
  - platform: device
    device_id: !input button
    domain: shelly
    type: btn_up
    subtype: button1
    id: btn1_up

action:
  - choose:
      - conditions:
          - condition: trigger
            id: btn1_down
        sequence: !input downb1
      - conditions:
          - condition: trigger
            id: btn1_up
        sequence: !input upb1
