wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  power_save_mode: none

  ap:
    ssid: "${device_name}"
    password: 1

external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h

esphome:
  name: ${device_name}

esp32:
  board: esp32dev

captive_portal:

web_server:
  port: 80

ota:
  password: ${wifi_password}
  safe_mode: true
  reboot_timeout: 3min
  num_attempts: 3

logger:
#  baud_rate: 0
#  level: WARN

output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

rtttl:
  id: buzzer
  output: buzzer_out

uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200
  id: tf_uart

button:
  - platform: restart
    name: ${device_name} Restart
    id: restart_nspanel

api:
  services:
    # Service to play a song
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda "return song_str;"
    - service: upload_tft
      then:
        - lambda: "id(disp1).upload_tft();"
    - service: send_command
      variables:
        cmd: string
      then:
        - lambda: 'id(disp1).send_command_printf("%s", cmd.c_str());'
